{
 "title": "PG_OVERVIEW_DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_server",
    "label": "Server",
    "query": "select server_name from tools.servers where disabled is false"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(servers.$db_server.postgresql-localhost.pg_bkends-*)"
    }
   ]
  },
  {
   "title": "Read Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.disk-nvme0n1.disk_octets.read"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.disk-nvme0n1.disk_octets.write"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.interface-ens3.if_octets.rx"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.interface-ens3.if_octets.tx"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.cpu-even-average.cpu-user"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.cpu-even-average.cpu-steal"
    }
   ]
  },
  {
   "title": "Autovacuum Workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_autovacuums"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_connections.active"
    }
   ]
  },
  {
   "title": "Longest Active Query",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_query_length"
    }
   ]
  },
  {
   "title": "Waiting Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_connections.locked"
    }
   ]
  },
  {
   "title": "Longest waiting Query",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_wait_length"
    }
   ]
  },
  {
   "title": "Idle in Transaction",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_connections.idle_transaction"
    }
   ]
  },
  {
   "title": "Root Mount Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.df-root.df_complex-free"
    }
   ]
  },
  {
   "title": "Mount Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.df-mnt-db.df_complex-free"
    }
   ]
  },
  {
   "title": "Longest Autovacuum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "servers.$db_server.postgresql-localhost.pg_autovacuum_length"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.cpu-even-average.cpu-user,1)"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.memory.memory-used,1)"
    }
   ]
  },
  {
   "title": "Disk Root Free",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.df-root.df_complex-free,1)"
    }
   ]
  },
  {
   "title": "Disk Mount Free",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.df-mnt-db.df_complex-free,1)"
    }
   ]
  },
  {
   "title": "Read Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk-{xvdb,nvme0n1}.disk_octets.read,1)"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk-{xvdb,nvme0n1}.disk_octets.write,1)"
    }
   ]
  },
  {
   "title": "Network Recieve",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.interface-ens{3,5}.if_octets.rx,1)"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.*.interface-ens{3,5}.if_octets.tx,1)"
    }
   ]
  }
 ]
}